### ISSUE TITLE
获取密码双重验证能不能关闭掉

### ISSUE THREAD

**Issue by jhsswl** [yuyan075500/ops-api#4]
默认的admin超级管理员获取密码也需要认证，能不能再配置文件中直接短信和mfa都禁用掉。

**Comment by yuyan075500** [comment]
因为存入系统的账号密码属于敏感信息，如果不需要认证就可以获取的话，万一系统账号被攻击者获取，那可以随意获取这些账号信息，那样存在很大的安全风险。

考虑到对于频繁获取密码的需求，认证通过后，默认是在10分钟内可以不需要认证即可获取，超过时间后需要再次认证。

MFA也是系统认证环节，用户真实性校验重要的一个步骤，建议还是开启。如果麻烦的话可以参考官方文档，配置下钉钉、企业微信或者飞书的扫码认证，这样更方便。

https://github.com/yuyan075500/ops-api/blob/main/deploy/dingtalk.md
https://github.com/yuyan075500/ops-api/blob/main/deploy/wechat.md
https://github.com/yuyan075500/ops-api/blob/main/deploy/feishu.md
