### ISSUE TITLE
分配资产账号给某个系统账户，但这个系统账户登录系统后看不到

### ISSUE THREAD

**Issue by Spinestars** [yuyan075500/ops-api#6]
内容如题

**Comment by yuyan075500** [comment]
默认管理员拥有系统所有权限，其它用户需要分配对应的权限才能看到【账号管理】的对应菜单选项，你需要为其先分配对应的菜单和接口权限后才能看到。如果你已经分配了还是无法看到，提供下对应的操作截图

**Comment by Spinestars** [comment]
可以只分配只读权限么？我尝试将账号管理分配给普通用户，他也有创建账号的权限

**Comment by yuyan075500** [comment]
普通用户如果需要使用账号管理功能，你需要分配以下权限：
![image](https://github.com/user-attachments/assets/6408b504-3e41-4981-93c4-575f581cf663)


默认情况下，分配以上权限后相关的用户都拥有创建账号的权限。如果账号所有者非自己（包括admin账号），那么只能获取该账号的密码，不能做其它任何操作。
